### PR TITLE
small rewordings and typos

### PR DESCRIPTION
**Pull request by hohMiyazawa**
An example pull request, in case you want to give the whole merging process a try. This will come up a lot if you are working with multiple contributors.

### CODE REVIEW

**Review by umgefahren — APPROVED** [review]
Thanks for the contribution! Please consider contributing further to this project. I would enjoy to work with you.

**Comment by umgefahren** [comment]
I approve the changes, but you have to transit the copyright to me, that I'm allowed to relicense this. I will never make this closed source, I just want to remove the GPL License one day for a more permissive license. Just to make it actually usable.

**Comment by hohMiyazawa** [comment]
I'm rather fond of the GPL myself, and if your intention is to never make this closed source, that's one of the key qualities of the license.

I do however not wish to cause any problems for you down the line, so I will probably be happy to any license arrangements you propose.

I hereby license my contribution under a dual GPLv3 and MIT license. If that's not enough and you need a full transfer of copyright (not customary for open source projects), please repeat that request and I will do so. (That said, I would be unlikely to claim many rights for a very superficial derivative change).

**Comment by umgefahren** [comment]
I explained everything here: https://github.com/umgefahren/image-comp-lib-rust/wiki/Contributions-and-Licensing
Please accept what I wrote. I hope you understand. If you are not okay with this, hit me up, we might find an agreement.

**Comment by hohMiyazawa** [comment]
Well, that clarified your intent, though I must warn against the plan about rolling a custom license.

Requiring all contributions to transfer copyright would make people think twice about contributing, and for many, including me, it's a definitive no-go. If someone ever has an idea for improving the software, forking their own project would then be much preferable to contributing to the original project because of this requirement.

Nevertheless, for this specific pull request, I'm posting your suggested sentence:
"I accept the contribution agreement which can be found at the wiki of this repository."

**Comment by umgefahren** [comment]
Thank you. The irony. I'll change it to MIT

**Comment by umgefahren** [comment]
I'm sorry that I had to bother you. I hope I didn't kill your amazing spirit.
I hope you are fine with the new license.

**Comment by hohMiyazawa** [comment]
Considering the purpose of this pull request was to sort out problems related to contribution, it seems to have been very successful.

**Pull request merged**
